# Generated by Django 5.2.4 on 2026-05-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Return Requested", "Return Requested"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
